apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwrite
  template:
    metadata:
      labels:
        app: appwrite
    spec:
      containers:
        - name: appwrite
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
