apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: appwrite-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: appwrite
  endpoints:
    - port: http
      interval: 15s
  namespaceSelector:
    matchNames:
      - appwrite
